SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE tree
  MODIFY COLUMN inode BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  MODIFY COLUMN parent BIGINT(20) UNSIGNED,
  ADD CONSTRAINT `childToParent` FOREIGN KEY (parent) REFERENCES tree (inode) ON DELETE CASCADE ON UPDATE CASCADE,
  Engine=InnoDB ROW_FORMAT=COMPRESSED;
SET FOREIGN_KEY_CHECKS=1;
