
ALTER TABLE tree
  MODIFY COLUMN parent BIGINT(20) UNSIGNED,
  ADD CONSTRAINT `childToParent` FOREIGN KEY (parent) REFERENCES tree (inode) ON DELETE CASCADE ON UPDATE CASCADE,
  Engine=InnoDB ROW_FORMAT=COMPRESSED;
